# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  deploy:
    docker:
      - image: debian
    working_directory: /content
    steps:
      - checkout
      - run:
          name: Copy content to production
          command: |
            cd /
            tar -zcvf content.tar.gz /content
            apt-get update
            apt-get -y install openssh-client
            scp -o StrictHostKeyChecking=no content.tar.gz root@softsideoftech.com:
            ssh -o StrictHostKeyChecking=no root@softsideoftech.com 'tar -xvf content.tar.gz'
            ssh -o StrictHostKeyChecking=no root@softsideoftech.com 'service softside restart'
workflows:
  version: 2
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master